import Head from "next/head";
import Image from "next/image";
import { DownArrow } from "../components/DownArrow/DownArrow";
import { MyDescription } from "../components/Home/MyDescription";
import { MyImage } from "../components/Home/MyImage";
import { NavButton } from "../components/NavButton/NavButton";
import { Project } from "../components/Project/Project";
import styles from "../styles/Home.module.scss";
import { SiLeetcode } from "react-icons/si";
import { RiGithubLine } from "react-icons/ri";
import { Link } from "../components/Home/Link";
import NextLink from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Suman Biswas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.nav_container}>
          <NextLink href="/">
            <Image
              src={"/home/logo.svg"}
              width={45}
              height={45}
              alt="logo.svg"
            />
          </NextLink>
          <NavButton />
        </nav>
        <div className={styles.home_main}>
          <MyDescription />
          <MyImage />
        </div>
        <div className={styles.home_footer}>
          <DownArrow />
          <div className={styles.links_container}>
            <Link site="github" link="https://github.com/sumanbiswas7">
              <RiGithubLine fill="#fff" size={20} />
            </Link>
            <Link site="leetcode" link="https://leetcode.com/sumanbiswas7/">
              <SiLeetcode fill="#fff" />
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
      <Project />
    </div>
  );
}
