import Head from "next/head";
import Image from "next/image";
import { DownArrow } from "../components/DownArrow/DownArrow";
import { MyDescription } from "../components/Home/MyDescription";
import { MyImage } from "../components/Home/MyImage";
import { NavButton } from "../components/NavButton/NavButton";
import { Project } from "../components/Project/Project";
import styles from "../styles/Home.module.scss";
import { SiLeetcode } from "react-icons/si";
import { RiGithubLine } from "react-icons/ri";
import { Link } from "../components/Home/Link";
import NextLink from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Suman Biswas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page_container}>
        <main className={styles.main}>
          <nav className={styles.nav_container}>
            <NextLink href="/">
              <Image
                src={"/home/logo.svg"}
                width={45}
                height={45}
                alt="logo.svg"
              />
            </NextLink>
            <NavButton />
          </nav>
          <div className={styles.home_main}>
            <MyDescription />
            <MyImage />
          </div>
          <div className={styles.home_footer}>
            <DownArrow />
            <div className={styles.links_container}>
              <Link site="github" link="https://github.com/sumanbiswas7">
                <RiGithubLine fill="#fff" size={20} />
              </Link>
              <Link site="leetcode" link="https://leetcode.com/sumanbiswas7/">
                <SiLeetcode fill="#fff" />
              </Link>
            </div>
          </div>
        </main>

        <footer className={styles.footer}></footer>
        <Project
          id={1}
          name="vivid"
          next="moviezine"
          imageUrl="./projects/img_vivid.png"
          logoUrl="./projects/logo_vivid.png"
          link_github=""
          link_project=""
          background="#50251c"
          techs={["React Native", "Cloudinary", "Firebase"]}
          description="vivid is a social media app for android and ios where people can share
           images, like, comment and many more..."
        />
        <Project
          id={2}
          imgWidth="32vmax"
          name="moviezine"
          next="nutshell"
          imageUrl="./projects/img_moviezine.png"
          logoUrl="./projects/logo_moviezine.png"
          link_github="https://github.com/sumanbiswas7/moviezine"
          link_project="https://moviezine.vercel.app/"
          background="#182309"
          techs={["NextJS", "S3", "Sass", "PostgreSQL", "GraphQL"]}
          description="website where everyone can share their favourite movie recommendations and see movies recommended by others"
        />
        <Project
          id={3}
          imgWidth="32vmax"
          name="nutshell"
          next="NFT"
          imageUrl="./projects/img_nutshell.png"
          logoUrl="./projects/logo_nutshell.png"
          link_github=""
          link_project=""
          background="#41260B"
          techs={["React Native", "Cloudinary", "Firebase"]}
          description="The cheapest and simplest way to make your own fully customizable restaurant menu app."
        />
      </div>
    </div>
  );
}
